# Generated by Django 3.2.5 on 2021-10-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=30)),
                ('email', models.EmailField(default=0, max_length=60)),
                ('phone_number', models.IntegerField(default=0)),
                ('location', models.CharField(default='no location', max_length=60)),
            ],
        ),
    ]
