# Generated by Django 3.2.5 on 2021-10-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthCaretsuppliestracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
