# Generated by Django 3.2.5 on 2021-10-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthCaretsuppliestracker', '0002_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='no status', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='no data', max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.TextField(default='no data', max_length=255)),
                ('donor', models.ForeignKey(default=' ', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='healthCaretsuppliestracker.donor')),
                ('hospital', models.ForeignKey(default=' ', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='healthCaretsuppliestracker.hospital')),
                ('order_status', models.ForeignKey(default='no status', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='healthCaretsuppliestracker.status')),
            ],
        ),
    ]
