# Generated by Django 3.2.5 on 2021-10-08 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthCaretsuppliestracker', '0003_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='donor',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='healthCaretsuppliestracker.donor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hospital',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='healthCaretsuppliestracker.hospital'),
        ),
    ]
