# Generated by Django 3.2.5 on 2021-10-08 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthCaretsuppliestracker', '0004_auto_20211008_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='donor',
            field=models.ForeignKey(default='no donor', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='healthCaretsuppliestracker.donor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hospital',
            field=models.ForeignKey(default='no hospital', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='healthCaretsuppliestracker.hospital'),
        ),
    ]
